config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings do
    resources :orders
  end

  get 'pages/about'
  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  if Rails.env.development?
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
  else
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
                      :storage => :dropbox,
                      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                      :path => ":style/:id_:filename"
  end

  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :state, presence: true
  
  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Produto cadastrado com sucesso!.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Produto atualizado com sucesso!.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  def show
  end

  def edit
  end

  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:name, :description, :price, :image)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    flash[:notice] = "Obrigado por comprar!"

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address, :city, :state)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<center><p>Universidade de Brasília - 2018</p></center>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">IMarket</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Sobre", pages_about_path %></li>
      <li><%= link_to "Contato", pages_contact_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vendas <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Gerenciar Produtos", seller_path %></li>
            <li><%= link_to "Histórico de Vendas", sales_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Histórico de Compra", purchases_path %></li>
            <li><%= link_to "Editar Conta", edit_user_registration_path %></li>
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Inscrever-se", new_user_registration_path %></li>
        <li><%= link_to "Entrar", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IMarket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> proibiu esta compra de ser salva:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :Nome %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Descrição %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Preço %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Imagem %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <% if current_user.recipient.blank? %>
    <br>
    <h1>Informações da Conta Bancária</h1>

    <div class="form-group">
      <%= label_tag :País %>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :Endereço %>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag :Número_da_conta %>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editando Compras</h1>
<%= render 'form' %>
<%= link_to 'Mostrar', @listing, class: "btn btn-link" %> |
<%= link_to 'Voltar', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron" align="center">
  <h1>IMarket</h1>
  <h3>Não deixe nada perder</h3>
</div>

<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Vendedor: #{listing.user.name}" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <%= link_to "Novo Produto", new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } %>
<% end %>

app/views/listings/new.html.erb
<h1>Novo Produto</h1>
<br><br>
<%= render 'form' %>
<%= link_to 'Voltar', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Imagem</th>
    <th class="center">Nome</th>
    <th class="center">Descrição</th>
    <th class="center">Preço</th>
    <th class="center">Ação</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td>
        <%= image_tag listing.image.url(:thumb) %>
      </td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Ver", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Editar", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Apagar', listing, method: :delete, data: { confirm: "Tem certeza?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Novo Produto', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>
    <br>
    <div class="center">
      <%= link_to "Comprar agora", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
    </div>
  </div>
</div>

<% if current_user == @listing.user %>
  <%= link_to 'Editar', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Voltar', listings_path, class: "btn btn-link" %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  <div class="col-md-8">

    <%= form_for([@listing, @order]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= f.label :Endereço %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :Cidade %>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :Estado %>
        <%= f.text_field :state, class: "form-control" %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :Número_do_cartão, "Número do Cartão" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :Código_de_segurança, "Código de Segurança" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag nil, "Data de Vencimento" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Comprar Produto", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>
<%= link_to 'Voltar', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Histórico de Compra</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Imagem</th>
    <th class="center">Item</th>
    <th class="center">Preço</th>
    <th class="center">Vendedor</th>
    <th class="center">Data da Compra</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.seller.name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Novo Produto', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Histórico de Vendas</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Imagem</th>
    <th class="center">Item</th>
    <th class="center">Preço</th>
    <th class="center">Cliente</th>
    <th class="center">Data da Venda</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.buyer.name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Novo Produto', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %>
<% end %>

app/views/pages/about.html.erb
<center><h1>Bem Vindo ao IMarket</h1>
	<br><br>
<h3>Uma solução inteligente para se desfazer de produtos culinários que não tem utilidade.</h3></center>
<br><br><br>

app/views/pages/contact.html.erb
<center><h1>Este projeto possui fins acadêmicos. Qualquer dúvida entrar em contato com a <b>Universidade de Brasília</b>.</h1></center>